apiVersion: v1
kind: Secret
metadata:
  name: devboard-secrets
  namespace: devboard

type: Opaque
data:
  POSTGRES_PASSWORD:  ZGV2Ym9hcmQ=
  POSTGRES_DB:  ZGV2Ym9hcmQ= # this decodes to devboard
  POSTGRES_URL: cG9zdGdyZXM6Ly9kZXZib2FyZDpkZXZib2FyZEBwb3N0Z3Jlczo1NDMyL2RldmJvYXJkP3NzbG1v # pstgresurl decode
# stringData:
  # POSTGRES_URL: postgres://devboard:devboard@postgres:5432/devboard?sslmode=disable
