name: Backend Build, Scan & Push

on:
  workflow_call:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Docker Setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (Local)
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        continue-on-error: true
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:latest
          format: 'table'
          output: 'trivy-backend-report.txt'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-backend-report
          path: trivy-backend-report.txt

      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:latest

