name: CB
on: 
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/resuable-workflow.yml
    with:
      env: prod
      app_name: devboard
    secrets: 
      token: ${{ secrets.DOCKER_TOKEN }}
