name: CB
on: 
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/resuable-workflow.yml
    with:
      env: prod
      app_name: devboard
    secrets: 
      token: ${{ secrets.DOCKER_TOKEN }}
  job2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.build.outputs.data }}"
      
