#Goal- I have a  build, push,   devboard frontend and backend  code, then push the images to Docker Hub
name: CI

on:
    push:
        branches: [advanced]

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json
            - name: Install npm packages
              run: npm ci
              working-directory: frontend
            
            - name: run linter
              run: npm run lint
              working-directory: frontend

            - name: Run Tests
              run: npm run test
              working-directory: frontend

            - name: Set up Docker
              uses: docker/setup-docker-action@v5
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v7
              with:
                context: ./frontend
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard:latest
    #  backend:


    backend:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-go@v6
              with:
                go-version: '1.22'
                go-version-file: 'go.mod'
                cache-dependency-path: go.sum
            - name: Run go formater
              run: 'go fmt'
              working-directory: backend
            
            - name: Run go vet
              run: go vet
              working-directory: backend

            - name: Run Tests
              run: go test
              working-directory: backend

            - name: Set up Docker
              uses: docker/setup-docker-action@v5
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v7
              with:
                context: ./backend
                push: true
                tags:  ${{ vars.DOCKERHUB_USERNAME }}/devboard:latest
  


