#Goal- I have a  build, push, test our devboard frontend and backend for code, then push the images to Docker Hub
name: CI

on:
    push:
        branches: [advanced]

jobs:
    code-lint:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v7
            - name: setup nodejs
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: github actions\frontend\package-lock.json
            - name: Install npm packages
              run: npm ci
            
            - name: run linter
              run: npm run lint
            - name: run tests
              run: run npm test

    #     frontend:
    #         steps:

    #     code:
    #     build:
    #     test:
    #     push:
        
    #  backend:
    #     code:
    #     build:
    #     test:
    #     push:


