name: devboard
on:
  push:
    branches: master
    paths: .github/workflows/devboard.yml
jobs:
  CI:
    runs-on: [self-hosted, linux]
    steps:
      - name: code-checkout
        uses: actions/checkout@v7
