# Goal - I have to lint, Build, Test the code for frontened and backened 
# then push images in dockerhub

name: devprthreetierci

on:
    push:
        branches: [advanced]

jobs:
    frontend:
            #github runner pe chalega
            runs-on: ubuntu-latest
            steps: 
                # code idhar lane ke liye
                - name: checkout code
                  uses: actions/checkout@v7

                # linting pahle kaam kre, iske liye code node js pe hua hai so node js pahle setup kro
                - name: setup NodeJs
                  uses: actions/setup-node@v6
                  # node js ka versionn vagera mention ke liye
                  with:
                    node-version: '20'
                    cache: npm
                    cache-dependency-path: frontend/package-lock.json

                # npm package ko install krne ke liye npm ci means npm clean install
                - name: install npm packages
                  run: npm ci
                  working-directory: frontend

                  

                # linter ko chalane ke liye
                - name: run linter
                  run: npm run lint
                  working-directory: frontend
                  
                # test krne ke liye try
                - name: run tests
                  run: npm run test  
                  working-directory: frontend
            
                - name: Log in to Docker Hub
                  uses: docker/login-action@v4
                  with:
                    username: ${{vars.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}

                - name: Build and Push
                  uses: docker/build-push-action@v7
                  with:
                    context: ./frontend
                    push: true
                    tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:latest
  

    
    
  #