name: DevSecOps

on:
  push:
    branches:
      - master
      - feat/dora-sota

  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  dependency-checks:
    uses: ./.github/workflows/dependency-scan.yml

  docker-checks:
    uses: ./.github/workflows/docker-scans.yml

  sonar-qube:
    uses: ./.github/workflows/sonar-scan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  code-tests:
    uses: ./.github/workflows/code-tests.yml

  docker-build-scan-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - code-quality
      - code-tests
      - sonar-qube
      - docker-checks
      - dependency-checks
      - secret-scanning
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/docker-push.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}