name: Dockerfile Security Scan

on:
  workflow_call:

jobs:
  dockerfile-security:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - backend
          - frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Dockerfile lint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: ${{ matrix.service }}/Dockerfile