name: secret
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: status
        if:  ${{ 'secrets.MY_SECRET' != '' }}
        run: echo " secret exists" 
      - name: print
        run: echo " ${{ secrets.MY_SECRET_MESSAGE }}"
        

  
