# Goal - to ensure no secrets have been leaked in the code.

name: Secret Scanning
on:
  workflow_call:

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      # Git leeks is used to scan the code for any secrets that have been leaked in the code by checking full commit history and the current code.
      - name: Gitleeks scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
